/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school.management.system;

import java.awt.Color;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class LoginWindow extends javax.swing.JFrame {

    private final Timer timer;
    private final TimerTask task;
    public int y = 0, z = 0;
    public boolean isDecreasing, colorPlay=false;
    public LoginWindow() {
        initComponents();
        
        // Automatically changing the Login JFrame bg color
        timer = new Timer();
        task = new TimerTask(){
            @Override
            public void run () {
                if(y==255){
                    isDecreasing = true;
                    y=255;z=255;
                }else if(y==0){
                    isDecreasing = false;
                    y=0;z=0;
                }
                // Incremental
                if(!isDecreasing){
                    // R:0-255, G:0-255, B:0-255
                    boardPanel.setBackground(new Color(160,y,((z*2>255)?y:z*2)));
                    y++;z++;
                }// Decremental
                if(isDecreasing){
                    boardPanel.setBackground(new Color(160,y,((z*2>255)?y:z*2)));
                    y--;z--;                            
                }              
            }
        };
        timer.schedule(task, new Date(),35);
        // EOF timer
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boardPanel = new javax.swing.JPanel();
        logAsLabel = new javax.swing.JLabel();
        loginCmBox = new javax.swing.JComboBox<>();
        pwdlabel = new javax.swing.JLabel();
        unameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        pwdField = new javax.swing.JPasswordField();
        signInBtn = new javax.swing.JButton();
        signUpLabel = new javax.swing.JLabel();
        aboutUsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setResizable(false);

        logAsLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        logAsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logAsLabel.setText("LOG IN");
        logAsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logAsLabelMouseClicked(evt);
            }
        });

        loginCmBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Teacher", "Admin", "Principal" }));
        loginCmBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginCmBoxActionPerformed(evt);
            }
        });

        pwdlabel.setText("Password:");

        unameLabel.setText("User Name:");

        nameField.setText("name");

        pwdField.setToolTipText("password");

        signInBtn.setText("Sign In");
        signInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInBtnActionPerformed(evt);
            }
        });

        signUpLabel.setForeground(new java.awt.Color(0, 0, 204));
        signUpLabel.setText("Sign Up");
        signUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpLabelMouseClicked(evt);
            }
        });

        aboutUsLabel.setForeground(new java.awt.Color(0, 51, 204));
        aboutUsLabel.setText("About Us");
        aboutUsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutUsLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout boardPanelLayout = new javax.swing.GroupLayout(boardPanel);
        boardPanel.setLayout(boardPanelLayout);
        boardPanelLayout.setHorizontalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(logAsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginCmBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(boardPanelLayout.createSequentialGroup()
                            .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pwdlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(unameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameField)
                                .addGroup(boardPanelLayout.createSequentialGroup()
                                    .addComponent(pwdField, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(signInBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(signUpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(aboutUsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                .addGap(67, 67, 67))
        );
        boardPanelLayout.setVerticalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logAsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginCmBox, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(pwdField)
                    .addComponent(signInBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(aboutUsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginCmBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginCmBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginCmBoxActionPerformed

    private void signInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInBtnActionPerformed
        nameField.setText("You clicked the Sign in button");
    }//GEN-LAST:event_signInBtnActionPerformed

    private void aboutUsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsLabelMouseClicked
        AboutUs sisi = new AboutUs();
        sisi.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        sisi.setVisible(true);
    }//GEN-LAST:event_aboutUsLabelMouseClicked

    private void signUpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpLabelMouseClicked
        SignUpForm sign = new SignUpForm();
        sign.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        sign.setLocation(500, 200);
        sign.setVisible(true);
    }//GEN-LAST:event_signUpLabelMouseClicked

    private void logAsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logAsLabelMouseClicked
        if(!colorPlay){
            timer.cancel();
        }else{
            colorPlay = true;
        }
    }//GEN-LAST:event_logAsLabelMouseClicked
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutUsLabel;
    public static javax.swing.JPanel boardPanel;
    private javax.swing.JLabel logAsLabel;
    private javax.swing.JComboBox<String> loginCmBox;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField pwdField;
    private javax.swing.JLabel pwdlabel;
    private javax.swing.JButton signInBtn;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JLabel unameLabel;
    // End of variables declaration//GEN-END:variables
}
